# Generated by Django 4.2.7 on 2023-11-11 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokeAPI', '0002_pokemon_abilities_pokemon_image_pokemon_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPokemon',
            fields=[
                ('pokemon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pokeAPI.pokemon')),
                ('base_experience', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('_id', models.PositiveIntegerField()),
                ('is_default', models.BooleanField()),
                ('moves', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('types', models.TextField()),
            ],
            bases=('pokeAPI.pokemon',),
        ),
    ]
